import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';

const $=id=>document.getElementById(id), canvas=$('game'), mini=$('minimap'), mc=mini.getContext('2d');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8fb8d9);scene.fog=new THREE.FogExp2(0xa6bfd0,.0019);const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,1200);
const hemi=new THREE.HemisphereLight(0xcce8ff,0x26311d,1.6),sun=new THREE.DirectionalLight(0xfff0ce,3);sun.position.set(110,170,70);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(hemi,sun);
const WORLD=520,BLOCK=62,ROAD=18,RIVER=225,clock=new THREE.Clock(),loader=new GLTFLoader(),textureLoader=new THREE.TextureLoader();
const S={money:2500,hp:100,wanted:0,time:.28,inCar:null,shot:0,mission:0},input={x:0,y:0,sprint:false,shoot:false,brake:false,keys:{}},cars=[],npcs=[],cops=[],obstacles=[],shops=[];let playerAngle=0;
const M={facades:[0xd7c7ae,0xc4b9a8,0xa8b6bd,0xd9d6cf,0xb08d76,0xc7b59b,0x8f9fa7].map(c=>mat(c,.8)),asphalt:mat(0x303236,.96),walk:mat(0x9a9b96,.9),grass:mat(0x537a42,1),water:new THREE.MeshPhysicalMaterial({color:0x2376a8,roughness:.2,transparent:true,opacity:.9})};
function mat(c,r=.8,m=.04){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}function add(g,m,x,y,z){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}function prog(n,t){$('loadingBar').style.width=n+'%';$('loadingText').textContent=t}
function texCanvas(text,bg='#182235',fg='#fff'){const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,512,160);x.fillStyle=fg;x.textAlign='center';x.textBaseline='middle';x.font='900 54px system-ui';x.fillText(text,256,80);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
async function ph(slug){try{const j=await (await fetch('https://api.polyhaven.com/files/'+slug)).json();let url;const walk=(o,p=[])=>{if(url||!o||typeof o!=='object')return;if(o.url&&p.includes('1k')&&p.some(v=>v==='Diffuse'||v==='diffuse')&&/\.(jpg|png)$/i.test(o.url))url=o.url;for(const[k,v]of Object.entries(o))walk(v,[...p,k])};walk(j);if(!url)return;return await new Promise((r,e)=>textureLoader.load(url,t=>{t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;r(t)},0,e))}catch{}}
async function materials(){const[a,c]=await Promise.all([ph('asphalt_01'),ph('concrete_pavement')]);if(a){a.repeat.set(8,8);M.asphalt=new THREE.MeshStandardMaterial({map:a,roughness:.96})}if(c){c.repeat.set(4,4);M.walk=new THREE.MeshStandardMaterial({map:c,roughness:.92})}}
function ground(){const g=add(new THREE.PlaneGeometry(WORLD,WORLD),M.grass,0,-.04,0);g.rotation.x=-Math.PI/2;const w=add(new THREE.PlaneGeometry(44,WORLD),M.water,RIVER,.12,0);w.rotation.x=-Math.PI/2}
function roads(){for(let i=-3;i<=3;i++){const p=i*BLOCK;add(new THREE.BoxGeometry(ROAD,.12,WORLD),M.asphalt,p,.03,0);add(new THREE.BoxGeometry(WORLD,.12,ROAD),M.asphalt,0,.03,p);for(let k=-4;k<=4;k++){add(new THREE.BoxGeometry(.16,.02,4.6),mat(0xf2e4ab,.65),p,.105,k*38);add(new THREE.BoxGeometry(4.6,.02,.16),mat(0xf2e4ab,.65),k*38,.105,p)}}for(let i=-3;i<3;i++)for(let j=-3;j<3;j++)add(new THREE.BoxGeometry(BLOCK-ROAD+4,.28,BLOCK-ROAD+4),M.walk,(i+.5)*BLOCK,.16,(j+.5)*BLOCK);for(const z of[-124,0,124]){add(new THREE.BoxGeometry(44,.14,ROAD+4),M.asphalt,RIVER,.08,z);add(new THREE.BoxGeometry(44,.3,3),M.walk,RIVER,.18,z-11);add(new THREE.BoxGeometry(44,.3,3),M.walk,RIVER,.18,z+11)}}
const names=['NOVA MARKET','CITY CAFÉ','GRANIVEL MOTORS','24/7 SHOP','URBAN GYM','PIZZA POINT','TECH HUB','FRESH MART','BARBER 21','CENTRAL PHARMACY','RIVER HOTEL','METRO FASHION'];
function building(x,z,w,d,h,i){add(new THREE.BoxGeometry(w,h,d),M.facades[i%M.facades.length],x,h/2+.3,z);obstacles.push({x,z,w:w/2+.5,d:d/2+.5});add(new THREE.BoxGeometry(w+.5,.7,d+.5),mat(i%2?0x4d5961:0x62554f,.9),x,h+.65,z);const wm=new THREE.MeshStandardMaterial({color:0x8fbdd0,roughness:.22,metalness:.15,emissive:0x152a35,emissiveIntensity:.3});for(let y=4;y<h-2;y+=4)for(let px=-w/2+2;px<w/2-1;px+=3.4){const q=new THREE.Mesh(new THREE.PlaneGeometry(1.7,1.8),wm);q.position.set(x+px,y,z+d/2+.012);scene.add(q)}if(i%3===0){const n=names[i%names.length],q=new THREE.Mesh(new THREE.PlaneGeometry(9,2.1),new THREE.MeshBasicMaterial({map:texCanvas(n)}));q.position.set(x,3.4,z+d/2+.03);scene.add(q);shops.push({x,z:z+d/2+3,n})}}
function city(){let n=0;for(let i=-3;i<3;i++)for(let j=-3;j<3;j++){const x=(i+.5)*BLOCK,z=(j+.5)*BLOCK;if(Math.abs(x-RIVER)<34)continue;const cnt=1+((i*j+9)%3);for(let q=0;q<cnt;q++){const a=q/cnt*Math.PI*2;building(x+Math.cos(a)*10*(cnt>1),z+Math.sin(a)*10*(cnt>1),cnt>1?13:31,cnt>1?14:30,13+((n+q)%5)*5,n++)}}}
function lamp(x,z){const pm=mat(0x252a2d,.45,.72);add(new THREE.CylinderGeometry(.11,.16,6,8),pm,x,3,z);add(new THREE.BoxGeometry(2.1,.1,.1),pm,x+.9,5.8,z);add(new THREE.SphereGeometry(.2,10,8),new THREE.MeshStandardMaterial({color:0xffedba,emissive:0xffcf6a,emissiveIntensity:2}),x+1.8,5.66,z);const l=new THREE.PointLight(0xffd78c,0,14,2);l.position.set(x+1.8,5.6,z);l.userData.street=1;scene.add(l)}
function sign(x,z,t='40'){add(new THREE.CylinderGeometry(.07,.07,2.7,7),mat(0x60656b,.5,.7),x,1.35,z);const q=new THREE.Mesh(new THREE.PlaneGeometry(1.2,1.2),new THREE.MeshBasicMaterial({map:texCanvas(t,'#fff','#111'),side:THREE.DoubleSide}));q.position.set(x,2.45,z);scene.add(q)}
function tree(x,z,s=1){add(new THREE.CylinderGeometry(.23,.37,3*s,8),mat(0x75543b,1),x,1.5*s,z);add(new THREE.IcosahedronGeometry(1.7*s,1),mat(0x3f7b42,1),x,3.9*s,z)}
function props(){for(let i=-3;i<=3;i++){const p=i*BLOCK;for(let k=-3;k<=3;k++){const q=k*BLOCK+22;lamp(p+11,q);lamp(q,p-11);if((i+k)%2===0)sign(p+12,q+5,String([30,40,50][Math.abs(i+k)%3]))}}for(let i=0;i<90;i++){const x=(Math.random()-.5)*430,z=(Math.random()-.5)*430;if(![-3,-2,-1,0,1,2,3].some(v=>Math.abs(x-v*BLOCK)<15||Math.abs(z-v*BLOCK)<15)&&Math.abs(x-RIVER)>28)tree(x,z,.7+Math.random()*.5)}}
function human(color=0x3568a8){const g=new THREE.Group(),skin=mat(0xd6a47d,.8),shirt=mat(color,.86),pants=mat(0x252d39,.9);let q=new THREE.Mesh(new THREE.SphereGeometry(.34,14,10),skin);q.position.y=1.77;g.add(q);q=new THREE.Mesh(new THREE.CapsuleGeometry(.4,.72,4,9),shirt);q.position.y=1.04;g.add(q);for(const x of[-.24,.24]){q=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.6,4,8),pants);q.position.set(x,.35,0);q.userData.leg=x;g.add(q)}for(const x of[-.56,.56]){q=new THREE.Mesh(new THREE.CapsuleGeometry(.1,.56,4,8),skin);q.position.set(x,1.13,0);g.add(q)}g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
const player=human(0x18385f);player.position.set(-15,0,18);scene.add(player);function valid(x,z){if(Math.abs(x)>255||Math.abs(z)>255)return false;if(Math.abs(x-RIVER)<20&&![-124,0,124].some(v=>Math.abs(z-v)<13))return false;return !obstacles.some(o=>Math.abs(x-o.x)<o.w&&Math.abs(z-o.z)<o.d)}
function target(n){for(let i=0;i<20;i++){const x=n.position.x+(Math.random()-.5)*70,z=n.position.z+(Math.random()-.5)*70;if(valid(x,z)){n.userData.t=new THREE.Vector3(x,0,z);return}}}
function npc(){const n=human(new THREE.Color().setHSL(Math.random(),.45,.4));do n.position.set((Math.random()-.5)*380,0,(Math.random()-.5)*380);while(!valid(n.position.x,n.position.z));n.userData={speed:.8+Math.random()*1.1,phase:Math.random()*6.2,alive:true};target(n);scene.add(n);npcs.push(n)}
const CARBASE='https://raw.githubusercontent.com/Arslan12216775/kenney_car-kit/master/Models/GLB%20format/',files=['sedan.glb','suv.glb','taxi.glb','van.glb','truck.glb','police.glb','ambulance.glb'];const templates=[];
function fakeCar(c=0x315f89){const g=new THREE.Group();let q=new THREE.Mesh(new THREE.BoxGeometry(3.2,1,5.8),mat(c,.35,.4));q.position.y=.75;g.add(q);q=new THREE.Mesh(new THREE.BoxGeometry(2.6,.9,2.9),mat(0x86adbe,.2,.2));q.position.set(0,1.5,-.15);g.add(q);for(const x of[-1.45,1.45])for(const z of[-1.9,1.9]){q=new THREE.Mesh(new THREE.CylinderGeometry(.5,.5,.3,14),mat(0x111111,.95));q.rotation.z=Math.PI/2;q.position.set(x,.48,z);g.add(q)}return g}
async function carAssets(){for(let i=0;i<files.length;i++){try{const g=(await loader.loadAsync(CARBASE+files[i])).scene;g.scale.setScalar(1.6);g.rotation.y=Math.PI;templates.push(g)}catch{templates.push(fakeCar(new THREE.Color().setHSL(i/7,.55,.36)))}}}
function car(x,z,axis=0,traffic=true,k=0){const o=(templates[k%templates.length]||fakeCar()).clone(true);o.position.set(x,.12,z);o.rotation.y=axis?Math.PI/2:0;scene.add(o);const c={o,speed:traffic?8+Math.random()*4:0,h:o.rotation.y,traffic,k,cop:false};cars.push(c);return c}function traffic(){for(let i=-3;i<=3;i++){const p=i*BLOCK;for(let k=-2;k<=2;k++){car(p-3,k*85-18,0,true,i+k+8);car(k*85+18,p+3,1,true,i-k+9)}}}
function setWanted(v){S.wanted=THREE.MathUtils.clamp(v,0,5);$('wanted').textContent='★'.repeat(S.wanted)+'☆'.repeat(5-S.wanted)}function ui(){$('money').textContent='$ '+Math.round(S.money).toLocaleString('hu-HU');$('healthBar').style.width=S.hp+'%'}
function nearest(){let b=null,d=4.6;for(const c of cars){if(c.cop)continue;const x=c.o.position.distanceTo(player.position);if(x<d){d=x;b=c}}return b}function action(){if(S.inCar){player.position.copy(S.inCar.o.position).add(new THREE.Vector3(3,0,0));player.visible=true;S.inCar=null;$('speed').classList.add('hidden')}else{const c=nearest();if(c){S.inCar=c;c.traffic=false;player.visible=false;$('speed').classList.remove('hidden');if(S.mission===0){S.mission=1;$('mission').textContent='Küldetés: menj a River Hotelhez.'}}}}
function updatePlayer(dt){if(S.inCar)return;let x=Math.abs(input.x)>.05?input.x:(input.keys.d?1:0)-(input.keys.a?1:0),y=Math.abs(input.y)>.05?input.y:(input.keys.s?1:0)-(input.keys.w?1:0);if(Math.hypot(x,y)>.05){const a=Math.atan2(camera.position.x-player.position.x,camera.position.z-player.position.z),dx=x*Math.cos(a)+y*Math.sin(a),dz=-x*Math.sin(a)+y*Math.cos(a),sp=(input.sprint||input.keys.shift)?7:4.4,nx=player.position.x+dx*sp*dt,nz=player.position.z+dz*sp*dt;if(valid(nx,nz)){player.position.x=nx;player.position.z=nz}playerAngle=Math.atan2(dx,dz);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,playerAngle,.2)}}
function updateCar(dt){if(!S.inCar)return;const c=S.inCar,th=-input.y+(input.keys.w?1:0)-(input.keys.s?1:0),st=input.x+(input.keys.d?1:0)-(input.keys.a?1:0);c.speed+=th*18*dt;c.speed*=input.brake?.93:.986;c.speed=THREE.MathUtils.clamp(c.speed,-9,30);c.h-=st*1.6*Math.min(1,Math.abs(c.speed)/7)*dt*Math.sign(c.speed||1);const x=c.o.position.x+Math.sin(c.h)*c.speed*dt,z=c.o.position.z+Math.cos(c.h)*c.speed*dt;if(valid(x,z)){c.o.position.x=x;c.o.position.z=z}else c.speed*=-.25;c.o.rotation.y=c.h;$('speedValue').textContent=Math.round(Math.abs(c.speed)*3.6)}
function shoot(){if(S.shot>0)return;S.shot=.25;setWanted(Math.max(1,S.wanted));const pos=S.inCar?S.inCar.o.position:player.position,ray=new THREE.Raycaster(pos.clone().add(new THREE.Vector3(0,1.4,0)),new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion),0,80),alive=npcs.filter(n=>n.userData.alive),hit=ray.intersectObjects(alive,true)[0];if(hit){let r=hit.object;while(r.parent&&!alive.includes(r))r=r.parent;if(alive.includes(r)){r.userData.alive=false;r.rotation.z=Math.PI/2;S.money+=100;setWanted(Math.min(5,S.wanted+1));ui()}}}
function spawnCop(){const t=S.inCar?S.inCar.o.position:player.position,a=Math.random()*6.28,c=car(t.x+Math.sin(a)*55,t.z+Math.cos(a)*55,0,false,5);c.cop=true;cops.push(c)}
function tickNPC(dt){const threat=S.wanted?(S.inCar?S.inCar.o.position:player.position):null;for(const n of npcs){if(!n.userData.alive)continue;let t=n.userData.t;if(threat&&n.position.distanceTo(threat)<23)t=n.position.clone().add(new THREE.Vector3().subVectors(n.position,threat).normalize().multiplyScalar(35));const d=new THREE.Vector3().subVectors(t,n.position);if(d.length()<2){target(n);continue}d.normalize();const x=n.position.x+d.x*n.userData.speed*dt,z=n.position.z+d.z*n.userData.speed*dt;if(valid(x,z)){n.position.x=x;n.position.z=z}else target(n);n.rotation.y=Math.atan2(d.x,d.z)}}
function tickCars(dt){for(const c of cars){if(!c.traffic||c===S.inCar||c.cop)continue;c.o.position.x+=Math.sin(c.h)*c.speed*dt;c.o.position.z+=Math.cos(c.h)*c.speed*dt;for(const k of['x','z'])if(c.o.position[k]>235)c.o.position[k]=-235;else if(c.o.position[k]<-235)c.o.position[k]=235}if(S.wanted&&cops.length<Math.min(5,S.wanted+1)&&Math.random()<dt*.16)spawnCop();const t=S.inCar?S.inCar.o.position:player.position;for(const c of cops){const d=new THREE.Vector3().subVectors(t,c.o.position),a=Math.atan2(d.x,d.z);c.h=THREE.MathUtils.lerp(c.h,a,dt*1.7);c.speed=13+S.wanted*3;c.o.rotation.y=c.h;c.o.position.x+=Math.sin(c.h)*c.speed*dt;c.o.position.z+=Math.cos(c.h)*c.speed*dt;if(d.length()<4.5){S.hp-=15*dt;ui();if(S.hp<=0){S.hp=100;S.money=Math.max(0,S.money-250);setWanted(0);player.position.set(-15,0,18);ui()}}}}
function cam(dt){const t=S.inCar?S.inCar.o.position:player.position,h=S.inCar?S.inCar.h:player.rotation.y,d=S.inCar?13:8.5,y=S.inCar?6:4.4,p=new THREE.Vector3(t.x-Math.sin(h)*d,t.y+y,t.z-Math.cos(h)*d);camera.position.lerp(p,1-Math.pow(.001,dt));camera.lookAt(t.x,t.y+1.2,t.z)}
function day(dt){S.time=(S.time+dt*.0035)%1;const a=S.time*Math.PI*2,k=THREE.MathUtils.clamp(Math.sin(a)*.75+.35,.08,1);sun.position.set(Math.cos(a)*140,Math.sin(a)*170,80);sun.intensity=.2+k*3;hemi.intensity=.2+k*1.5;scene.background.setHSL(.58,.42,.08+k*.57);scene.fog.color.copy(scene.background);scene.traverse(o=>{if(o.isPointLight&&o.userData.street)o.intensity=k<.38?2.8:0})}
function map(){mc.fillStyle='#0b1720';mc.fillRect(0,0,180,180);mc.strokeStyle='#687780';mc.lineWidth=7;for(let i=-3;i<=3;i++){const p=90+i*BLOCK/WORLD*324;mc.beginPath();mc.moveTo(p,0);mc.lineTo(p,180);mc.stroke();mc.beginPath();mc.moveTo(0,p);mc.lineTo(180,p);mc.stroke()}const p=S.inCar?S.inCar.o.position:player.position;mc.fillStyle='#fff';mc.beginPath();mc.arc(90+p.x/WORLD*324,90+p.z/WORLD*324,5,0,7);mc.fill();for(const c of cops){mc.fillStyle='#f44';mc.beginPath();mc.arc(90+c.o.position.x/WORLD*324,90+c.o.position.z/WORLD*324,3,0,7);mc.fill()}}
function mission(){const p=S.inCar?S.inCar.o.position:player.position;if(S.mission===1){const h=shops.find(s=>s.n==='RIVER HOTEL')||{x:170,z:170};if(Math.hypot(p.x-h.x,p.z-h.z)<14){S.mission=2;S.money+=750;setWanted(2);$('mission').textContent='Küldetés: rázd le a rendőröket!';ui()}}if(S.mission===2&&S.wanted===0){S.mission=3;S.money+=1500;$('mission').textContent='Küldetés teljesítve. +$1 500';ui()}}
function controls(){addEventListener('keydown',e=>{input.keys[e.key.toLowerCase()]=1;if(e.key.toLowerCase()==='e')action();if(e.code==='Space')shoot()});addEventListener('keyup',e=>delete input.keys[e.key.toLowerCase()]);const joy=$('joy'),knob=$('knob');let id;const move=e=>{const r=joy.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,m=43,l=Math.hypot(x,y),s=l>m?m/l:1;input.x=x/m*s;input.y=y/m*s;knob.style.transform=`translate(${input.x*m}px,${input.y*m}px)`};joy.onpointerdown=e=>{id=e.pointerId;joy.setPointerCapture(id);move(e)};joy.onpointermove=e=>{if(e.pointerId===id)move(e)};joy.onpointerup=()=>{id=null;input.x=input.y=0;knob.style.transform='translate(0,0)'};const bind=(id,key,fn)=>{const e=$(id);e.onpointerdown=x=>{x.preventDefault();input[key]=1;fn&&fn()};e.onpointerup=e.onpointercancel=()=>input[key]=0};bind('btnAction','action',action);bind('btnShoot','shoot',shoot);bind('btnSprint','sprint');bind('btnBrake','brake')}
async function init(){prog(6,'PBR textúrák…');await materials();prog(18,'Utak és folyó…');ground();roads();prog(35,'Épületek, boltok, táblák…');city();props();prog(52,'Autók…');await carAssets();traffic();prog(72,'Emberek és NPC-k…');for(let i=0;i<42;i++)npc();controls();ui();prog(100,'Kész');setTimeout(()=>{$('loading').style.opacity=0;setTimeout(()=>$('loading').remove(),500)},250);requestAnimationFrame(loop)}
function loop(){const dt=Math.min(.033,clock.getDelta());S.shot=Math.max(0,S.shot-dt);if(input.shoot)shoot();updatePlayer(dt);updateCar(dt);tickNPC(dt);tickCars(dt);cam(dt);day(dt);mission();map();const n=S.inCar?1:nearest();$('interaction').style.opacity=n?1:0;$('interaction').textContent=S.inCar?'E / gomb: kiszállás':n?'E / gomb: beszállás':'';if(S.wanted&&cops.every(c=>c.o.position.distanceTo(S.inCar?S.inCar.o.position:player.position)>80)&&Math.random()<dt*.045)setWanted(S.wanted-1);renderer.render(scene,camera);requestAnimationFrame(loop)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});init();
